import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

 

export const metadata: Metadata = {
  title: "Pitch, Vote and grow with YC Directory",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className=""
      >
        {children}
      </body>
    </html>
  );
}
